In [2]:
# Packages and dependencies
from ipywidgets import *
import pandas as pd
import glob
import numpy as np
import os
import re
import json
import requests
import csv
import requests
from io import StringIO 
import gzip

In [3]:
%matplotlib inline

In [4]:
### Nao adicionar

# Calculate Fisher Exact Test

# Criate python dict, use it to generate and run the queries

encpy = pd.read_csv("/Users/Carol/Desktop/tfA/dataTables/encode/encodeMasterRace.csv")

encpy.head()

,description,TF1,cell1,gene1,organism,Enc16,CreedsDN,Overlap16down,TF2,cell2,...,CreedsDN.1,overlap15down,pvalue15down,TF4,cell4,gene4,CreedsUP,Overlap15up,pvalue15up,totalEncode15
0,SETDB1_K562_31,SETDB1,K562,31,hg19,956,345,2,SETDB1,K562,...,345.0,0,1.0,SETDB1,K562,31,252,0,1.0,0
1,MYC_HepG2_1820,MYC,HepG2,1820,hg19,2000,217,2,MYC,HepG2,...,217.0,0,1.0,MYC,HepG2,1820,353,0,1.0,0
2,CTCF_astrocyteofthecerebellum_124,CTCF,astrocyteofthecerebellum,124,hg19,2000,286,1,CTCF,astrocyteofthecerebellum,...,286.0,0,1.0,CTCF,astrocyteofthecerebellum,124,314,0,1.0,0
3,CTCF_bronchialepithelialcell_124,CTCF,bronchialepithelialcell,124,hg19,2000,286,1,CTCF,bronchialepithelialcell,...,286.0,0,1.0,CTCF,bronchialepithelialcell,124,314,0,1.0,0
4,CTCF_cardiacfibroblast_124,CTCF,cardiacfibroblast,124,hg19,2000,286,1,CTCF,cardiacfibroblast,...,286.0,0,1.0,CTCF,cardiacfibroblast,124,314,0,1.0,0

In [5]:
# for line in encpy:
#      print(encpy["description"])

In [6]:
# python

encodeA = pd.read_csv('/Users/Carol/Desktop/porra/ENCODE2016_UPDATE_PRONTO_FIM_transposed.csv',low_memory=False)
#encodeB = pd.read_csv('/Users/Carol/Desktop/porra/ENCODE_TF_ChIP-seq_2015_trabalhado_overlap2016_transposed.csv',sep=',',header=True)

encodeA.head()

/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (61,62,65,66,67,68,69,70,74,75,77,78,79,80,81,82,163,198,199,202,205,209,213,214,217,220,238,239,242,279,280,283,284,285,286,287,288,291,299,302,303,305,306,307,310,311,313,314,315,318,319,320,322,323,332,336,337,339,340,341,342,343,344,362,393,537,625,719,847,850,851,855,856,858,863,867,873,890,893,896,899,901,902,903,904,907,908,911,913,917,918,927,931) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,REST_H1hESC_hg19,TAF1_HeLaS3_hg19,REST_HepG2_hg19,ZBTB7A_K562_hg19,SIX5_K562_hg19,SIN3A_SKNSH_hg19,CBX3_K562_hg19,TRIM28_K562_hg19,JUND_SKNSH_hg19,JUND_T47D_hg19,...,TCF12_MELcellline_mm9,CHD2_ESE14_mm9,MAFK_ESE14_mm9,USF1_MELcellline_mm9,IRF4_CH12.LX_mm9,MEF2A_CH12.LX_mm9,MEF2A_MELcellline_mm9,TCF12_CH12.LX_mm9,USF1_CH12.LX_mm9,NRF1_CH12.LX_mm9
0,LINC01420,POLK,MMP24,PTGES3L,CIAO1,SSTR5-AS1,ARFRP1,LOC221946,PSG8,ZSWIM8,...,Zfp607,Zfp526,Gm4285,Saraf,Slc39a9,Gm12191,Exosc4,Znhit1,Dtx3,Dolk
1,POLR2K,MMEL1,ZNF586,LOC100996351,MRPL10,PRKCSH,ABHD16A,DUS2,CLIP3,GBA,...,C530005A16Rik,Gm1976,Tram1,Dph5,Rrnad1,Sphk2,Nsrp1,Zscan22,Magt1,Fbln1
2,ZNF528,PPP2R3C,THAP10,PNMA5,MRPL51,PPP1R7,MIR6718,NRXN2,FTSJ3,SNORD18B,...,Cox11,Mrps31,Erlin2,Polb,Abcb7,Znhit1,Mrpl1,Fam132b,Hdac5,8-Mar
3,ATP6V0B,LOC101927156,LINC00893,ESRRA,MAGEA8-AS1,MIR6866,TBCCD1,MGC45922,SNORD78,DUOXA1,...,C87436,Eaf1,3110082I17Rik,Nagpa,Uba7,Hnrnpr,Aaas,Rbm8a,Kidins220,Rasd1
4,TARBP2,PSMA1,WRAP53,LINGO4,STK36,ST3GAL6-AS1,VPS9D1,NLRP4,C9orf43,LOC104054148,...,Cog4,Dnajc27,Mrpl1,Dph1,Tcea1,Zfp369,Fcgr1,Lrrc58,Vapa,Sgpp1

In [7]:
# list with the headers(name) of samples from list A
goListA = list(encodeA)
#goListA

# list with the headers(name) of samples from list B
goListB=list(encodeA)
#goListB

In [8]:
# Create dataframe from lists

dfA= pd.DataFrame(goListA,columns=['ListA'])
dfA.head()

dfB = pd.DataFrame(goListB,columns=['ListB'])
dfB.head()

              ListB
0  REST_H1hESC_hg19
1  TAF1_HeLaS3_hg19
2   REST_HepG2_hg19
3  ZBTB7A_K562_hg19
4    SIX5_K562_hg19

In [9]:
# Acessing data # Defining overlap to be tested
# Create a dataframe for tested where row has list A| listB

# Append Columns to "matrix", 
go = []
for row in dfA['ListA']:
    a = 'go.obj <- newGeneOverlap(encodeA$%s' %(row)
    go.append(a)
go = pd.DataFrame(go)
# go.head()

gob = []
for row in dfB['ListB']:
    b = 'encodeB$%s'%(row) 
    gob.append(b)
gob = pd.DataFrame(gob)
# gob.head()

## Concatenayed Columns
gobject = pd.concat([go,gob],axis=1)
gobject.columns = ['A', 'B']
gobject.to_csv('gobject.csv',index=False) # save it to open in R in the other tab, since R stopped working here

gobject.head()

                                                   A                         B
0  go.obj <- newGeneOverlap(encodeA$REST_H1hESC_hg19  encodeB$REST_H1hESC_hg19
1  go.obj <- newGeneOverlap(encodeA$TAF1_HeLaS3_hg19  encodeB$TAF1_HeLaS3_hg19
2   go.obj <- newGeneOverlap(encodeA$REST_HepG2_hg19   encodeB$REST_HepG2_hg19
3  go.obj <- newGeneOverlap(encodeA$ZBTB7A_K562_hg19  encodeB$ZBTB7A_K562_hg19
4    go.obj <- newGeneOverlap(encodeA$SIX5_K562_hg19    encodeB$SIX5_K562_hg19

# R code

### R code that used the previous dataframe to create the GeneOverlap command

%%R

for (i in gobject) {
  b <- paste(sprintf('(%s,%s,genome.size=20805),',gobject$a,gobject$b))
#   print(b)
  write.table(b, "enc15vs16freeOverlapMap2.csv", quote=FALSE, row.names=F, col.names=FALSE, sep="\t")
  }


# Gives out 
#go.obj <- newGeneOverlap(encodeA$REST_H1hESC_hg19,encodeB$REST_H1hESC_hg19,,genome.size=20805)

%%R

# Load library
library(GeneOverlap)

# Read in R tables
encodeA <- read.table('/Users/Carol/Desktop/porra/ENCODE2016_UPDATE_PRONTO_FIM_transposed.csv',sep=',', header=TRUE)
encodeB <- read.table('/Users/Carol/Desktop/porra/ENCODE_TF_ChIP-seq_2015_trabalhado_overlap2016_transposed.csv',sep=',', header=TRUE)

gobject <- read.table('/Users/Carol/Desktop/tfA/gobject.csv',sep=',', header=TRUE)

# summary(gobject)
#nrow(gobject)

sapply(encodeA,length)
sapply(encodeB,length)

genome = 20805 # RefSeq Hg19 

#go.obj <- newGeneOverlap(encodeA$REST_H1hESC_hg19,encodeB$REST_H1hESC_hg19,genome.size=genome)
#print(go.obj)

%%R
# List of overlap comparisons. Ufahhhh...

for (i in gobject) {
  b <- paste(sprintf('(%s,%s,genome.size=20805)',gobject$a,gobject$b))
#   print(b)
  write.table(b, "enc15vs16freeOverlapMap2.csv", quote=FALSE, row.names=F, col.names=FALSE, sep="\t")
  }

# Overlap output

In [9]:
# Clean/ Organize/ Standardize output from gene overlap comparisons.

In [10]:
import re

# List of words to delete
delete = ['size','#','\n','Index',]

# Data to keep 
words = ['listA', 'listB','Intersection','Overlapping p-value', 'Odds ratio','Union','Jaccard Index']


rep = re.compile(r'|'.join(delete))
keep = re.compile(r'|'.join(words))

data = []
with open('/Users/Carol/Desktop/tfA/ENCODEE15E15.csv') as f1:
    for line in f1:
        if keep.search(line):
            # replace all unwanted substrings
            line = rep.sub("", line.lstrip())     
            line=line.split('=')
#             print(line)
            data.append(line)

#print df
# type(data)

df = pd.DataFrame(data)

df.columns = ['category', 'value']
df['value'] = df.value.str.split(',').str.get(0)  # split value column at the , and que left side of string
# df.head(100)


# grouped = df.groupby('category')
# grouped.head()

df.head(10)

              category value
0               listA   2000
1               listB   1681
2        Intersection    175
3               Union   3506
4  Overlapping p-value  0.13
5           Odds ratio   1.1
6             Jaccard    0.0
7               listA   2000
8               listB   1174
9        Intersection     98

In [ ]:
labels=df['category']
labels = labels.drop_duplicates()
labels

In [ ]:
values=df
values
# df.loc[df['column_name'] == some_value]
# encode_metadata = encode_metadata[~encode_metadata.Biosample_treatments.isin(value_list_treatment)]

# listA = df[(df[1] == 'listA')]
# listB 
# Intersection 
# Union 
# Overlapping p-value
# Odds ratio
# Jaccard Index

df
listA = df[df['category'].str.contains("listA")]
listB = df[df['category'].str.contains("listB")]
intersection = df[df['category'].str.contains("Intersection")]
union = df[df['category'].str.contains("Union")]
pval= df[df['category'].str.contains("Overlapping p-value")]
odds= df[df['category'].str.contains("Odds ratio")]
jaccard= df[df['category'].str.contains("Jaccard Index")]


# Dropped category column and just kept the values column
# listA = listA.drop('category', axis=1)
listA = listA.T


# listB = listB.drop('category', axis=1)
listB = listB.T

# intersection = intersection.drop('category', axis=1)
Intersection = intersection.T

# union = union.drop('category', axis=1)
Union = union.T

# pval = pval.drop('category', axis=1)
pval = pval.T

# odds = odds.drop('category', axis=1)
odds = odds.T

# jaccard = jaccard.drop('category', axis=1)
# Jaccard Index = jaccard.T

# dff = listA.append(listB)
listA = listA.drop('category')
listA

In [ ]:
grouped = df.as_matrix(df, ncol=7, byrow=True)
grouped = df.groupby('category')
grouped.head()


### DICT desses dados#####
###nao usei 
#Created dictionary with the data
# data = pd.DataFrame({'category': ['listA', 'listB', 'Intersection', 'Union','Overlapping','Odds','Jaccard']}) 
# #*4, 'Ob1' : np.random.rand(16), 'Ob2' : np.random.rand(16)})
# data

# #create unique list of names
# uniqueCat = df.category.unique()

# # #create a data frame dictionary to store your data frames
# # DataFrameDict = { : pd.DataFrame for elem in uniqueCat}

# for key in DataFrameDict.keys():
#     DataFrameDict[key] = df[:][df.category == key]
    
# # DataFrameDict